# Nord
# Theme create by: https://github.com/rames-eltany
# Update by(sort by time):
# 
# Thanks for all contributor!!

# If you want to make border display just set it same as sidebar background color

# Code syntax highlight theme (you can go to https://github.com/alecthomas/chroma/blob/master/styles to find one you like)
code_syntax_highlight = "nord"

# ========= Border =========
file_panel_border = "#4c566a"
sidebar_border = "#2e3440"
footer_border = "#4c566a"

# ========= Border Active =========
file_panel_border_active = "#88c0d0"
sidebar_border_active = "#88c0d0"
footer_border_active = "#88c0d0"
modal_border_active = "#88c0d0"

# ========= Background (bg) =========
full_screen_bg = "#16161f"
file_panel_bg = "#16161f"
sidebar_bg = "#16161f"
footer_bg = "#16161f"
modal_bg = "#16161f"

# ========= Foreground (fg) =========
full_screen_fg = "#e5e9f0"
file_panel_fg = "#e5e9f0"
sidebar_fg = "#e5e9f0"
footer_fg = "#e5e9f0"
modal_fg = "#e5e9f0"

# ========= Special Color =========
cursor = "#88c0d0"
correct = "#88c0d0"
error = "#bf616a"
hint = "#8fbcbb"
cancel = "#d8dee9"
# Gradient color can only have two color!
gradient_color = ["#81a1c1", "#bf616a"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = "#74c7ec"
file_panel_top_path = "#74c7ec"
file_panel_item_selected_fg = "#bf616a"
file_panel_item_selected_bg = "#2e3440"

# ========= Sidebar Special Items =========
sidebar_title = "#0c9ac3"
sidebar_item_selected_fg = "#88c0d0"
sidebar_item_selected_bg = "#2e3440"
sidebar_divider = "#868686"

# ========= Modal Special Items =========
modal_cancel_fg = "#e5e9f0"
modal_cancel_bg = "#4c566a"

modal_confirm_fg = "#e5e9f0"
modal_confirm_bg = "#bf616a"

# ========= Help Menu =========
help_menu_hotkey = "#8fbcbb"
help_menu_title = "#81a1c1"